USE [master]
GO
/****** Object:  Database [ObligatorioDDA]    Script Date: 9/10/2025 20:52:50 ******/
CREATE DATABASE [ObligatorioDDA]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ObligatorioDDA', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\ObligatorioDDA.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ObligatorioDDA_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\ObligatorioDDA_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [ObligatorioDDA] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ObligatorioDDA].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [ObligatorioDDA] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [ObligatorioDDA] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [ObligatorioDDA] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [ObligatorioDDA] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [ObligatorioDDA] SET ARITHABORT OFF 
GO
ALTER DATABASE [ObligatorioDDA] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [ObligatorioDDA] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [ObligatorioDDA] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [ObligatorioDDA] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [ObligatorioDDA] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [ObligatorioDDA] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [ObligatorioDDA] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [ObligatorioDDA] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [ObligatorioDDA] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [ObligatorioDDA] SET  ENABLE_BROKER 
GO
ALTER DATABASE [ObligatorioDDA] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [ObligatorioDDA] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [ObligatorioDDA] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [ObligatorioDDA] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [ObligatorioDDA] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [ObligatorioDDA] SET READ_COMMITTED_SNAPSHOT ON 
GO
ALTER DATABASE [ObligatorioDDA] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [ObligatorioDDA] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [ObligatorioDDA] SET  MULTI_USER 
GO
ALTER DATABASE [ObligatorioDDA] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [ObligatorioDDA] SET DB_CHAINING OFF 
GO
ALTER DATABASE [ObligatorioDDA] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [ObligatorioDDA] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [ObligatorioDDA] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [ObligatorioDDA] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [ObligatorioDDA] SET QUERY_STORE = ON
GO
ALTER DATABASE [ObligatorioDDA] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200)-- WAIT_STATS_CAPTURE_MODE = ON)
--COMENTAMOS UN PEDACITO DEL CODIGO ANTERIOR XQ VISUAL NO LO RECONOCE BIEN Y DA ERROR PERO PARA CORRER LA BDD DEBERIAS DE SACAR EL COMENTARIO PARA QUE QUEDE TODO BIEN
GO
USE [ObligatorioDDA]
GO
/****** Object:  Table [dbo].[__EFMigrationsHistory]    Script Date: 9/10/2025 20:52:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[__EFMigrationsHistory](
	[MigrationId] [nvarchar](150) NOT NULL,
	[ProductVersion] [nvarchar](32) NOT NULL,
 CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY CLUSTERED 
(
	[MigrationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Jugadores]    Script Date: 9/10/2025 20:52:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Jugadores](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_Jugadores] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Partidas]    Script Date: 9/10/2025 20:52:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Partidas](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Estado] [int] NOT NULL,
	[TiempoPartida] [time](7) NULL,
	[MetaMadera] [int] NOT NULL,
	[MetaPiedra] [int] NOT NULL,
	[MetaComida] [int] NOT NULL,
 CONSTRAINT [PK_Partidas] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Recursos]    Script Date: 9/10/2025 20:52:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Recursos](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [int] NOT NULL,
 CONSTRAINT [PK_Recursos] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Registros]    Script Date: 9/10/2025 20:52:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Registros](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Id_Partida] [int] NOT NULL,
	[Id_Jugador] [int] NOT NULL,
	[TipoRecolectado] [int] NOT NULL,
	[Puntaje] [int] NOT NULL,
	[Fecha] [datetime2](7) NOT NULL,
 CONSTRAINT [PK_Registros] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Index [IX_Registros_Id_Jugador]    Script Date: 9/10/2025 20:52:51 ******/
CREATE NONCLUSTERED INDEX [IX_Registros_Id_Jugador] ON [dbo].[Registros]
(
	[Id_Jugador] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_Registros_Id_Partida]    Script Date: 9/10/2025 20:52:51 ******/
CREATE NONCLUSTERED INDEX [IX_Registros_Id_Partida] ON [dbo].[Registros]
(
	[Id_Partida] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Registros]  WITH CHECK ADD  CONSTRAINT [FK_Registros_Jugadores_Id_Jugador] FOREIGN KEY([Id_Jugador])
REFERENCES [dbo].[Jugadores] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Registros] CHECK CONSTRAINT [FK_Registros_Jugadores_Id_Jugador]
GO
ALTER TABLE [dbo].[Registros]  WITH CHECK ADD  CONSTRAINT [FK_Registros_Partidas_Id_Partida] FOREIGN KEY([Id_Partida])
REFERENCES [dbo].[Partidas] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Registros] CHECK CONSTRAINT [FK_Registros_Partidas_Id_Partida]
GO
USE [master]
GO
ALTER DATABASE [ObligatorioDDA] SET  READ_WRITE 
GO
