// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ObligatorioDDA.src.Data;

#nullable disable

namespace ObligatorioDDA.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251005234732_CambioTiempoPartidaATimeSpan")]
    partial class CambioTiempoPartidaATimeSpan
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ObligatorioDDA.src.Models.Jugador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Jugadores");
                });

            modelBuilder.Entity("ObligatorioDDA.src.Models.Partida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<int>("MetaComida")
                        .HasColumnType("int");

                    b.Property<int>("MetaMadera")
                        .HasColumnType("int");

                    b.Property<int>("MetaPiedra")
                        .HasColumnType("int");

                    b.Property<TimeSpan?>("TiempoPartida")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("Partidas");
                });

            modelBuilder.Entity("ObligatorioDDA.src.Models.Recurso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Nombre")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Recursos");
                });

            modelBuilder.Entity("ObligatorioDDA.src.Models.Registro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_Jugador")
                        .HasColumnType("int");

                    b.Property<int>("Id_Partida")
                        .HasColumnType("int");

                    b.Property<int>("Puntaje")
                        .HasColumnType("int");

                    b.Property<int>("TipoRecolectado")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Id_Jugador");

                    b.HasIndex("Id_Partida");

                    b.ToTable("Registros");
                });

            modelBuilder.Entity("ObligatorioDDA.src.Models.Registro", b =>
                {
                    b.HasOne("ObligatorioDDA.src.Models.Jugador", "Jugador")
                        .WithMany()
                        .HasForeignKey("Id_Jugador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ObligatorioDDA.src.Models.Partida", "Partida")
                        .WithMany("Registros")
                        .HasForeignKey("Id_Partida")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jugador");

                    b.Navigation("Partida");
                });

            modelBuilder.Entity("ObligatorioDDA.src.Models.Partida", b =>
                {
                    b.Navigation("Registros");
                });
#pragma warning restore 612, 618
        }
    }
}
